# Checking that required variables are set

- name: Checking that required variables are set
  when: vars[item] is undefined
  ansible.builtin.fail:
    msg: "{{ item }} is undefined"
  loop:
    - agent_root
    - bamboo_jar_file
    - bamboo_server_url
    - bamboo_version
    - capability_file
    - group
    - install_root
    - operating_system
    - service_name
    - user
  tags:
    - always
