# Checking that required variables are set

- name: Checking that required variables are set
  when: vars[item] is undefined
  ansible.builtin.fail:
    msg: "{{ item }} is undefined"
  loop:
    - bambooagent_agent_root
    - bambooagent_capability_file
    - bambooagent_group
    - bambooagent_install_root
    - bambooagent_jar_filename
    - bambooagent_jar_filename_full_path
    - bambooagent_service_name
    - bambooagent_user
    - bambooagent_version
    - bamboo_server_url
  tags:
    - always
