---
- name: Make sure the group exists
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Creating non-existing user
  ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ group }}"
    comment: "Bamboo agent"
    state: present
    createhome: true
    system: true
  register: user_output

- name: Fix home permissions
  ansible.builtin.file:
    path: "{{ user_output.home }}"
    state: directory
    owner: "{{ user }}"
    mode: "0755"
