---
- name: Check if the group exists
  ansible.builtin.group:
    name: "{{ bambooagent_group }}"
    state: present

- name: Check if the local user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ bambooagent_user }}"
    split: ':'
    fail_key: false

- name: Creating non-existing user
  ansible.builtin.user:
    name: "{{ bambooagent_user }}"
    comment: "Bamboo agent"
    state: present
    createhome: true
    system: true
  register: user

- name: Fix home permissions
  ansible.builtin.file:
    path: "{{ user.home }}"
    state: directory
    owner: "{{ bambooagent_user }}"
    mode: "0755"
