---
# Installs the service

- name: Create the installation folder
  ansible.builtin.file:
    path: "{{ install_root }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Copy bamboo jar into destination from existing file
  ansible.builtin.copy:
    src: "{{ bamboo_jar_file }}"
    dest: "{{ install_root }}/{{ jar_filename }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0744"

- name: Install the systemd config
  ansible.builtin.template:
    src: "ubuntu/etc/systemd/system/atlassian-bambooagent.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: "0644"

- name: Install the startup script
  ansible.builtin.template:
    src: "ubuntu/bamboo-startup.sh.j2"
    dest: "{{ install_root }}/bamboo-startup.sh"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Register and restart service
  ansible.builtin.assert:
    that: true
  changed_when: true
  notify:
    - Register service
    - Restart service
