---
# List of tasks

- name: Check variables
  ansible.builtin.import_tasks: check_vars.yml
  tags:
    - checks

- name: Install certificates
  ansible.builtin.import_tasks: install_certificates.yml
  tags:
    - certificates

- name: Configure user Ubuntu/macOS
  when: ansible_distribution != "Windows"
  ansible.builtin.import_tasks: create_user.yml
  tags:
    - create_user

- name: Configure user Windows
  when: ansible_distribution == "Windows"
  ansible.builtin.import_tasks: create_user_win.yml
  tags:
    - create_user

- name: Set defaults
  ansible.builtin.import_tasks: set_defaults.yml
  tags:
    - capability

- name: Install packages on Ubuntu
  when: ansible_distribution == "Ubuntu"
  ansible.builtin.import_tasks: install_packages.yml
  tags:
    - packages

- name: Install starter Ubuntu/macOS
  when: ansible_distribution != "Windows"
  ansible.builtin.import_tasks: install_starter.yml
  tags:
    - starter

# - name: Install python3
#   ansible.builtin.import_tasks: install_python3.yml
#   tags:
#     - python

# - name: Exiting
#   ansible.builtin.assert:
#     that:
#       - false

# - name: Configure capabilities
#   ansible.builtin.import_tasks: configure_capabilities.yml
#   tags:
#     - capabilities
