---
# List of tasks

- name: Check variables
  ansible.builtin.import_tasks: check_vars.yml
  tags:
    - checks

- name: Install certificate
  ansible.builtin.import_tasks: install_certificate.yml
  tags:
    - certificates

- name: Configure user Ubuntu/macOS
  when: ansible_distribution != "Windows"
  ansible.builtin.import_tasks: create_user_ubuntu.yml
  tags:
    - create_user

- name: Configure user Windows
  when: ansible_distribution == "Windows"
  ansible.builtin.import_tasks: create_user_win.yml
  tags:
    - create_user

- name: Exiting
  ansible.builtin.assert:
    that:
      - false

- name: Install starter
  ansible.builtin.import_tasks: install_starter.yml
  tags:
    - starter

- name: Configure capabilities
  ansible.builtin.import_tasks: configure_capabilities.yml
  tags:
    - capabilities
