---
# Reads the capability file
- name: Read remote capability file
  when: ansible_distribution != "Windows"
  block:
    - name: Check remote capability file exists
      ansible.builtin.stat:
        path: "{{ capability_file }}"
      register: stat_capability_exist

    - name: Read remote capability file content
      ansible.builtin.slurp:
        src: "{{ capability_file }}"
      when: stat_capability_exist.stat.exists
      register: capability_content_remote

    - name: Process remote capability file content
      ansible.builtin.set_fact:
        bamboo_capabilities: |
           {{ (bamboo_capabilities | default({})) |
              combine({item.split('=')[0].strip(): item.split('=')[1].strip()}) }}
      loop: "{{ (capability_content_remote['content'] | b64decode).split('\n') }}"
      when:
        - stat_capability_exist.stat.exists
        - item.strip()
        - item.split('=')[0].strip()

- name: '[BAMBOO] read remote capability file'
  block:
    - name: '[BAMBOO] read remote capability file'
      win_stat:
        path: "{{ capability_file }}"
      register: stat_capability_exist

    - name: '[BAMBOO] read remote capability file'
      slurp:
        src: "{{ capability_file }}"
      when: stat_capability_exist.stat.exists
      register: capability_content_remote

    # replacing \\\\ with just \\ (the capability should contain \\ for a single \)
    - name: '[BAMBOO] read remote capability file'
      set_fact:
        bamboo_capabilities: >-
          {{ (bamboo_capabilities | default({}))
             | combine({item.split('=')[0].strip(): (
                        item.split('=')[1].strip()
                        | regex_replace('(?<!\\\\)\\\\(?!\\\\)', '\\')
                        )
                       })
             }}
      loop: "{{ (capability_content_remote['content'] | b64decode).split('\n') }}"
      when:
        - stat_capability_exist.stat.exists
        - item.strip()
        - item.split('=')[0].strip()

  when:
    - ansible_os_family == "Windows"
