---
# Set defaults

- name: Read agent capability file
  ansible.builtin.include_tasks: read_capability.yml

- name: Declare default capabilities
  ansible.builtin.set_fact:
    capabilities: "{{ (capabilities | default({})) | combine({item.key: item.value}) }}"
  loop:
    - key: 'operating_system'
      value: "{{ operating_system }}"
    - key: agent_name
      value: "{{ ansible_fqdn }}"
    - key: osversion
      value: "{{ ansible_distribution_version.split('.')[:2] | join('.') }}"

- name: Update agent capability file
  ansible.builtin.include_tasks: write_capability.yml
