---
# Writes/updates the capability file

# non windows

- name: Create root directory
  ansible.builtin.file:
    path: "{{ capability_file | dirname }}"
    state: directory
    recurse: true
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Create capability
  ansible.builtin.file:
    path: "{{ capability_file }}"
    state: touch
    mode: "0444"

- name: Flush capabilities into file (new created, existing updated)
  ansible.builtin.lineinfile:
    dest: "{{ capability_file }}"
    state: present
    regexp: "^{{ item.key.strip() | replace('\\n', '') | replace('\\r', '') }}="
    line: "{{ item.key.strip() | replace('\\n', '') | replace('\\r', '') }}={{ item.value.strip() | replace('\\n', '') | replace('\\r', '') }}"
  loop: "{{ capabilities | dict2items }}"

- name: Remove empty lines from the capability file
  ansible.builtin.lineinfile:
    dest: "{{ capability_file }}"
    state: absent
    regexp: "^\\s*$"

- name: Remove capabilities from agents
  ansible.builtin.lineinfile:
    dest: "{{ capability_file }}"
    state: absent
    regexp: "^{{ item.strip() | replace('\\n', '') | replace('\\r', '') }}="
  loop: "{{ bamboo_capabilities_to_remove | default([]) }}"

# windows

- name: '[BAMBOO] Check if the agent file exists'
  win_stat:
    path: "{{ capability_file }}"
  when:
    - ansible_os_family == "Windows"
  register: win_stat_result

- name: Create root directory if file does not exist
  win_file:
    path: "{{ capability_file | dirname }}"
    state: directory
    recurse: yes
    owner: "{{ bambooagent_user }}"
    group: "{{ bambooagent_group }}"
    mode: "u+rwx,g+rw,o+rx"
  when:
    - ansible_os_family == "Windows"
    - not win_stat_result.stat.exists


# what a nightmare to escape \ with YAML...
- name: '[BAMBOO] Flush the capabilities into the agents file'
  win_lineinfile:
    dest: "{{ capability_file }}"
    state: present
    create: yes
    regexp: "^{{ item.key.strip() | replace('\\n', '') | replace('\\r', '') }}="
    line: >-
       {{ item.key.strip()
         | replace('\\n', '')
         | replace('\\r', '') }}={{ item.value.strip()
                                    | replace('\\n', '')
                                    | replace('\\r', '')
                                    | regex_replace('(?<!\\)\\(?!\\)', '\\\\') }}
  loop: "{{ bamboo_capabilities | dict2items }}"
  tags:
  - capability:write
  when:
    - ansible_os_family == "Windows"

- name: '[BAMBOO] Remove empty lines from the capability file'
  win_lineinfile:
    dest: "{{ capability_file }}"
    state: absent
    regexp: "^\\s*$"
  tags:
  - capability:write
  when:
    - ansible_os_family == "Windows"

- name: '[BAMBOO] Remove capabilities from agents'
  win_lineinfile:
    dest: "{{ capability_file }}"
    state: absent
    regexp: "^{{ item.strip() | replace('\\n', '') | replace('\\r', '') }}="
  loop: "{{ bamboo_capabilities_to_remove | default([]) }}"
  tags:
  - capability:write
  when:
    - ansible_os_family == "Windows"
