- name: Register init.d
  ansible.builtin.command: update-rc.d {{ service_name }} enabled
  register: output
  changed_when: output.rc != 0

- name: Register service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: reloaded
    enabled: true

- name: Restart service
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
    enabled: true

# - name: Restart bambooagent windows
#   ansible.windows.win_service:
#     name: "{{ bambooagent_service_name }}"
#     state: restarted
#   listen: "Restart bambooagent"
#   when:
#     - ansible_os_family == "Windows"
